database:
        image: postgres:9.4
        hostname: pg
        ports:
                - "5432:5432"
#        volumes:
#                - ./scripts:/scripts
#        entrypoint: "/scripts/entry.sh"
#        command:
#                - service postgresql status
api:
        restart: on-failure
        build: ./api
        volumes:
                - ./api:/app
        command: "--reload"
        links:
                - database
        ports:
                - "8000:8000"
apiambassador:
        image: cpuguy83/docker-grand-ambassador
        volumes:
                - /var/run/docker.sock:/var/run/docker.sock
        command: -name=chapter2_api_1
frontend:
        image: nginx
        volumes:
                - ./frontend/nginx.conf:/etc/nginx/nginx.conf
                
        links:
                - apiambassador:api
        ports:
                - "80:80"